### ISSUE TITLE
Add code for interop with R

### ISSUE THREAD

**Issue by behrica** [sbelak/huri#11]
I could contribute some code for dataframe interop with R here.
See initial discussion here:
https://groups.google.com/forum/#!topic/numerical-clojure/WMLw1p4cPOI

Let me know, if you are interested

**Comment by sbelak** [comment]
Definitely interested. Ideally you would do all the data manipulation in CLJ and use R for it's stats libraries. 

I'm not a huge fan of having essentially R one-liners in separate files, but that can be easily solved with a DSL on top.

**Comment by behrica** [comment]
I have something very basic working, the tests look like this:

```clojure
(ns r-df-interop.core-test
  (:require [clojure.test :refer :all]
            [r-df-interop.core :refer :all]
            [huri.core :as hc]
           ))

(deftest simpe-df
  (testing "simple df"
    (eval "rm(list=ls())")
    (let [df  [{:a 1 :b 2}{:a 10 :b 20}]]
      (assign-df-to-R "df_in" df)
      (is (= ["a" "b" ] (seq (eval "colnames(df_in)"))))
      (is (= [11.0] (seq(eval "sum(df_in$a)" )))))))


(deftest load_iris
  (testing "iris"
    (let [iris (get-df-from-R "iris")] 
      (is (= [:Sepal.Length :Sepal.Width :Petal.Length :Petal.Width :Species]
             (hc/cols iris)))
      (is (= [5.1 4.9]
             (take 2 (hc/col :Sepal.Length iris))
             ))
      (is (= ["setosa" "setosa"]
             (take 2 (hc/col :Species iris))
             )) )))


The code manages so far the conversion from String/Long/Factor columns between R data.frame and 
clojure maps.

The ugly part are the dependencies.
It needs ugly stuff in project.clj:

```clojure
jvm-opts [ 
             ~(str "-Djava.library.path=/home/carsten/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri:" (System/getProperty "java.library.path"))]

  :resource-paths [
                   "/home/carsten/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri/JRI.jar"
                   "/home/carsten/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri/JRIEngine.jar"
                   "/home/carsten/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri/REngine.jar"
                   "/home/carsten/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri/libjri.so"]

```
+ R_HOME set

**Comment by behrica** [comment]
I found a project, which basicaly does a large part of the data type conversions,
between Clojure and R/Rexp

I updated it do clojure 1.8.0
https://github.com/behrica/rincanter

It uses "core.matrix.dataset" and I decided to keep this for my new function  as well.
Like this, my use cases is already implemented with very little work.
https://github.com/behrica/rincanter/issues/3

To use is with huri, you needed to transform the data from row maps to core.matrix.dataset and back.

Currently it has still a dependeny to incanter (because it was based on incanter 1.5.6, which contained dataset),
but we have now a dataset implementation in clojure.core.matrix.dataset.
So I want to remove the dependecy to incanter all together.
This is tracked in:
https://github.com/behrica/rincanter/issues/4


I think we can close this issue here.
Please provide me with comments on the issues in the rincater project, in case you have any.
