### ISSUE TITLE
[question] any reason to use clojure-1.9.0-alpha but not 1.8.0?

### ISSUE THREAD

**Issue by randomizedthinking** [sbelak/huri#13]
Tried to integrate huri in my workflow, yet failed because I can't get clojure-1.9.0-alpha to work with many packages already in use.

Here  I wonder is there any particular reason to use `clojure-1.9.0-alpha`, any particular nice features it offers? This is just for my own curiosity. Thanks.

**Comment by sbelak** [comment]
I use clojure.spec quite a bit for input validation and data transformation. 

Shameless plug: I gave a talk about why I love spec last year at EuroClojure https://www.youtube.com/watch?v=-9dOZX-ERcM

**Comment by randomizedthinking** [comment]
I see... it is a valid reason, :).

On the other hand, lein does not work well with Java 9 till now based on my
own experience, so it would cause trouble for people who want to use huri.
