### ISSUE TITLE
Complains about clojure.spec not being found

### ISSUE THREAD

**Issue by sooheon** [sbelak/huri#3]
At some point after 1.9-alpha14 (which is what huri is on), the Clj dev team moved spec into the clojure.spec.alpha ns.

**Comment by sbelak** [comment]
Fixed with #4

**Comment by sooheon** [comment]
@sbelak, do you mind testing this and pushing a SNAPSHOT when you have the time? Thanks

**Comment by sbelak** [comment]
Shit, thought I did. Sorry. Done.
